#!/usr/bin/env python
import sys
import argparse
from libxvm.commands import COMMANDS, argparser


def main():
    argparser.add_argument('command', help='Run this command')
    argparser.add_argument('--help', '-h', action='store_true')
    argparser.epilog = "Run `xvm list` to see a list of available commands."
    ns, argv = argparser.parse_known_args()
    if ns.command and ns.command in COMMANDS:
        argparser.supress_positional('command')
        argparser.prog = '{} {}'.format(argparser.prog, ns.command)
        nextmain = COMMANDS[ns.command]
        nextmain(argparser)
    else:
        argparser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
